# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’

target 'Mantle+JSONTransformerExtension' do
	pod 'Mantle'
end

target 'Mantle+JSONTransformerExtensionTests' do
	pod 'Mantle'
end

